[en]
  LanguageName = "English"
  languageCode = "en-us"
  weight = 1
  # [en.params]
  #   linkedin = 'https://linkedin.com/simonheimlicher'

[de]
  LanguageName = "Deutsch"
  languageCode = "de-ch"
  weight = 2
  # [de.params]
  #   linkedin = 'https://linkedin.com/de/simonheimlicher'
