# Params for theme 'claris'
canonicalBaseURL = "https://simonheimlicher.github.io/hugo-claris-demo/"

showShare = false # Uncomment to not show share buttons on each post. Also available in each post's front matter.

# Top-level directories where your articles are located
# See config details here https://gohugo.io/functions/where/#mainsections
# Note: articles in these sections are styled differently:
# - The first paragraph is automatically treated as the lede
# - A drop cap is added to the second paragraph
mainSections = ["post", "technology"] # see config details here https://gohugo.io/functions/where/#mainsections

logo = "images/logo"

logoURL = "/"

# center logo on navbar
centerLogo = false # Set to "true" for centering or "false" for left aligned.

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "right" # if you prefer right change to 'right'

# Enforce dark or light mode irrespective of system settings of user
# You cannot enforce both modes at the same time. i.e by enforcing one mode,
# you priotise it over the other (by setting it to true).
# The color mode toggle UI will remain in place. That way, if a user prefers
# darkmode, they can have their way.
# enforceLightMode = false
# enforceDarkMode = false

# Maximum number of recent articles.
# numberOfRecentArticles = 3

# Maximum number of featured articles.
# numberOfRecentArticles = 3

# Maximum number of related articles.
numberOfRelatedArticles = 5

# Date format. Checkout https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference for details.
# dateFormat = "2006-01-02" # Default to "Jan 2, 2006".

# tell hugo where you store your icons e.g favicons. This is useful if you're using an apache server and there are conflicts >> see issue https://github.com/chipzoller/hugo-clarity/issues/74. If this is applicable to you, be sure to copy the contents of https://github.com/chipzoller/hugo-clarity/tree/master/static/icons to your preferred icons directory
# iconsDir = "icons/"

# Limit tags and categories to only include articles from the last x years
taxonomyMaxYears = 5

# Limit recent articles to only include articles from the last x years
recentMaxYears = 5

# Show a note indicating that an article is outdated after x years
outdatedAfterYears = 5
# Define sections whose content expires and should be flagged with a note
# after .Params.outdatedAfterYears
ephemeralSections = [
  "technology"
]

# toggle to true if you want to use custom fonts only.
# customFonts = true
# Serve font files from static instead of relying on Google Fonts servers
fontsSelfHosted = true

# Support IE 11 with JS polyfills / ponyfills
supportIE11 = true

sidebarTaxonomies = ["tags", "categories"]

[home]
  section = "_home"

[footer]
  section = "_footer"
  recentarticles = 3
  social = ['linkedin', 'twitter', 'github']

# Include meta tag robots = noindex, nofollow
# Exclude pages from sitemap
[hidden]
  # Sections within which all pages are hidden
  sections = ["_error", "_home", "_footer"]
  # Path elements below which all pages are hidden
  pathelements = ['confidential', 'private', 'hidden']

[website]
  name = "Hugo Claris Showcase"
  tagline = "Fluid portfolio and blog theme"

  # Description to be used for home page content meta tags (SEO).
  # Alternatively set this description in your homepage content file i.e content/_index.md. Whatever is set in the latter will take precedence
  description = "Showcase of the theme “Claris” for Hugo, the world’s fastest static site generator"

  # The year when ths website was created, this value is used in the copyright
  # notice of the footer.
  established = 2016

  # Profile of the main subject of this website
  # This is currently only used if there are no valid pages in section footer
  [website.profile]
    headline = "About Hugo Claris"
    text = "Fluid portfolio and blog theme for Hugo built by"
    link = "Simon Heimlicher"
    # URL for the 'read more' link below the profile, or set to false to not show the link
    url = "https://simon.heimlicher.com/about/"

  # [website.license]
  #   identifier = "CC BY-NC-ND 4.0"
  #   URL = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

[image]
  thumbnail = [
    "images/sh.com_site_thumbnail_1200x627.png",
    "images/sh.com_site_thumbnail_1200x675.png",
    "images/sh.com_site_thumbnail_1200x1200.png"
  ]


[responsive]
  [responsive.breakpoints]
    [responsive.breakpoints.width]
      # From this width upward, the mobile menu is hidden
      # and the full menu bar is shown
      mobileMenu = "40rem"

      # From this width upward, font size is set to regular size
      narrow = "44rem"

# Configuration of robots tag in head
[robots]
  index = true
  indeximages = false
  follow = true
  # Sections to be listed in robots.txt as being excluded from indexing
  # CAUTION: This will cause attackers to look at these sections in particular, so do not use this parameter to hide a section
  # robotsTxtDisallowSections = ["_error", "_home", "_footer"]

[social]
  [social.twitter]
    id = "simonheimlicher"
  [social.github]
    id = "simonheimlicher"
  [social.linkedin]
    id = "simonheimlicher"
  [social.stackoverflow]
    id = "617559/simon-heimlicher"

