# Define a subset of content directories to be used for development
module:
  mounts:
    - source: content
      target: content
      includeFiles:
        - '/*index.md'
    - source: content/about
      target: content/about
    - source: content/images
      target: content/images
    - source: content/technology
      target: content/technology
    - source: content/components/hero-image
      target: content/components/hero-image
    - source: content/components/feature-image
      target: content/components/feature-image
    - source: content/_footer
      target: content/_footer
      includeFiles:
        - '**/*index.md'
        - '**/profile.md'
        - recent-articles_post.md
        - recent-articles_technology.md

# NOTE: The following approach of defining empty keys
# leads to issues with spurious home pages being rendered
# that do not appear to be backed by files and thus
# do not get any params from the front matter, such as `.Title`
# taxonomies:
#   category:
#   tag:
#   series:

disableKinds:
  - RSS
  - taxonomy
  - term
